# Generated by Django 2.2.5 on 2019-11-10 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=150)),
                ('pwd', models.CharField(max_length=150)),
                ('cpwd', models.CharField(max_length=150)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedApp.Batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedApp.Course')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedApp.Course'),
        ),
    ]
