# Generated by Django 2.2.5 on 2019-11-10 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=150)),
                ('feedback', models.TextField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedApp.Batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedApp.Course')),
                ('uname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedApp.Registration')),
            ],
        ),
    ]
