# Generated by Django 2.2.5 on 2019-11-11 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedApp', '0004_remove_feedback_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
